name: rf-region-classifier
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - biopython
  - blast
  - pip
  - pip:
      - tqdm
